#ifndef SDKCONFIG_H
#define SDKCONFIG_H

/* ESP8266 Specific */
#define CONFIG_ESP8266_XTAL_FREQ_26 1
#define CONFIG_ESP8266_XTAL_FREQ 26
#define CONFIG_ESP8266_DEFAULT_CPU_FREQ_80 1
#define CONFIG_ESP8266_DEFAULT_CPU_FREQ_MHZ 80
#define CONFIG_SOC_IRAM_SIZE 0xC000
#define CONFIG_RESET_REASON 1
#define CONFIG_WIFI_PPT_TASKSTACK_SIZE 2048

/* FreeRTOS */
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_TASK_NOTIFICATIONS 1
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1024
#define CONFIG_FREERTOS_ISR_STACKSIZE 2048
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_FREERTOS_TIMER_STACKSIZE 2048
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 2

/* LwIP */
#define CONFIG_LWIP_TCP_MSS 1460
#define CONFIG_LWIP_TCP_TMR_INTERVAL 250
#define CONFIG_LWIP_TCP_MSL 60000
#define CONFIG_LWIP_TCP_MAXRTX 12
#define CONFIG_LWIP_TCP_SYNMAXRTX 6
#define CONFIG_LWIP_TCP_OVERSIZE_MSS 1
#define CONFIG_LWIP_MAX_SOCKETS 10
#define CONFIG_LWIP_MAX_ACTIVE_TCP 16
#define CONFIG_LWIP_MAX_LISTENING_TCP 16
#define CONFIG_LWIP_TCP_RTO_TIME 3000
#define CONFIG_LWIP_TCPIP_RECVMBOX_SIZE 32
#define CONFIG_LWIP_TCP_RECVMBOX_SIZE 6
#define CONFIG_LWIP_UDP_RECVMBOX_SIZE 6
#define CONFIG_LWIP_TCPIP_TASK_STACK_SIZE 2048
#define CONFIG_LWIP_TCP_SND_BUF_DEFAULT 2880
#define CONFIG_LWIP_TCP_WND_DEFAULT 5760
#define CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1
#define CONFIG_LWIP_IP4_FRAG 1
#define CONFIG_LWIP_IP4_REASSEMBLY 1
#define CONFIG_IP_LOST_TIMER_INTERVAL 120

/* Wi-Fi */
#define CONFIG_ESP8266_WIFI_RX_BUFFER_NUM 16
#define CONFIG_ESP8266_WIFI_RX_PKT_NUM 7
#define CONFIG_ESP8266_WIFI_TX_PKT_NUM 6
#define CONFIG_ESP8266_WIFI_NVS_ENABLED 1
#define CONFIG_WPA_SCAN_SSID_MAX_COUNT 4
#define CONFIG_IEEE80211W 1
#define CONFIG_SCAN_AP_MAX 99

/* System */
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_NEWLIB_STDOUT_ADDCR 1
#define CONFIG_ESP_CONSOLE_UART_NUM 0
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 4096
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2048
#define CONFIG_ESP_TIMER_TASK_STACK_SIZE 2048

#define IDF_VER "v3.4-nim"
#define __ESP_FILE__ __FILE__
#define ESP_PLATFORM 1

/* Memory Alignment */
#define MALLOC_CAP_8BIT      (1 << 0)
#define MALLOC_CAP_32BIT     (1 << 1)
#define MALLOC_CAP_DMA       (1 << 2)
#define MALLOC_CAP_PID2      (1 << 3)
#define MALLOC_CAP_PID3      (1 << 4)
#define MALLOC_CAP_PID4      (1 << 5)
#define MALLOC_CAP_PID5      (1 << 6)
#define MALLOC_CAP_PID6      (1 << 7)
#define MALLOC_CAP_PID7      (1 << 8)
#define MALLOC_CAP_INTERNAL  (1 << 9)
#define MALLOC_CAP_DEFAULT   (1 << 10)
#define MALLOC_CAP_INVALID   (1 << 31)

#endif
