# src/config_helper.nims
import os, strutils

# 1. Base Paths
# We need to find the library's 'src' directory.
var helperDir = ""
if fileExists(projectDir() / "src/esp_rtos.nim"):
  helperDir = projectDir() / "src"
elif fileExists(projectDir() / "../../src/esp_rtos.nim"):
  helperDir = projectDir().parentDir().parentDir() / "src"
else:
  let nimblePath = gorge("nimble path esp8266_sdk").strip()
  if nimblePath != "":
    helperDir = nimblePath / "src"

if helperDir == "":
  echo "Error: Could not find esp8266_sdk. Make sure it is installed or you are in the repo."
  quit(1)

let sdkBase = helperDir.parentDir()

# 2. Toolchain Detection
let toolchainExe = findExe("xtensa-lx106-elf-gcc")
let toolchainPath = if toolchainExe != "":
  toolchainExe.parentDir()
else:
  getHomeDir() / "esp/xtensa-lx106-elf/bin"

# Ensure toolchain is in PATH for any subprocesses
putEnv("PATH", toolchainPath & PathSep & getEnv("PATH"))

# 3. Path Settings
# Add the library's src directory to the search path
switch("path", helperDir)

# 4. Nim compiler settings for ESP8266
switch("cpu", "riscv32") # Placeholder for Xtensa
switch("os", "any")
switch("threads", "off")
switch("mm", "arc")
switch("define", "noSignalHandler")
switch("define", "dynlibOverrideAll")
switch("define", "useMalloc")
switch("gcc.exe", "xtensa-lx106-elf-gcc")
switch("gcc.linkerexe", "xtensa-lx106-elf-gcc")
switch("gcc.path", toolchainPath)
switch("gcc.options.linker", "")

# 5. Architecture specific flags
switch("passC", "-mlongcalls")
switch("passC", "-mtext-section-literals")
switch("passC", "-DICACHE_FLASH")
switch("passC", "-fstrict-volatile-bitfields")
switch("passC", "-ffunction-sections")
switch("passC", "-fdata-sections")
switch("passC", "-DCONFIG_IEEE80211W")
switch("passC", "-DLWIP_IPV6=1")
switch("passC", "-DESP_SUPPLICANT")
switch("passC", "-DCONFIG_WPA3_SAE")
switch("passC", "-D__bswap_16=__builtin_bswap16")
switch("passC", "-D__bswap_32=__builtin_bswap32")
switch("passC", "-DCONFIG_ESP8266_TIME_SYSCALL_USE_FRC1")

# Handle sdkconfig.h: user project > current dir > library default
if fileExists("src/sdkconfig.h"):
  switch("passC", "-include src/sdkconfig.h")
elif fileExists("sdkconfig.h"):
  switch("passC", "-include sdkconfig.h")
else:
  switch("passC", "-include " & helperDir / "default_sdkconfig.h")

# 6. Linker flags
switch("passL", "-Wl,--gc-sections")
switch("passL", "-nostdlib")

let sdkLdPath = sdkBase / "vendor/components/esp8266/ld"
switch("passL", "-L" & sdkLdPath)
switch("passL", "-T" & sdkLdPath / "esp8266.rom.ld")
switch("passL", "-T" & sdkLdPath / "esp8266.peripherals.ld")
switch("passL", "-T" & helperDir / "esp8266_nim.ld")

# Toolchain Libraries
switch("passL", "-L" & toolchainPath.parentDir() / "xtensa-lx106-elf/lib")

# Detect GCC versioned library path
let gccLibBase = toolchainPath.parentDir() / "lib/gcc/xtensa-lx106-elf"
if dirExists(gccLibBase):
  let dirs = listDirs(gccLibBase)
  if dirs.len > 0:
    switch("passL", "-L" & dirs[0])

switch("passL", "-lc")
switch("passL", "-lm")
switch("passL", "-lgcc")
switch("passL", "-L" & sdkBase / "vendor/components/esp8266/lib")
switch("passL", "-lnet80211 -lpp -lphy -lhal -lcore -lrtc -lclk -lsmartconfig")

# 7. Tasks
task flash, "Convert to bin and flash to ESP8266":
  let esptool = sdkBase / "vendor/components/esptool_py/esptool/esptool.py"
  # Try to find the elf file. Usually it's named after the project or 'main'
  var elfFile = "main"
  if not fileExists(elfFile):
    let files = listFiles(".")
    for f in files:
      if f.endsWith(".elf"):
        elfFile = f
        break
  
  if not fileExists(elfFile):
    echo "Error: Could not find ELF file to flash. Compile your project first."
    return

  let bin0 = elfFile & "-0x00000.bin"
  let bin1 = elfFile & "-0x10000.bin"
  
  exec "python3 " & esptool & " --chip esp8266 elf2image --flash_mode dio --flash_freq 40m --flash_size 4MB " & elfFile
  exec "python3 " & esptool & " --chip esp8266 --port /dev/ttyUSB0 --baud 115200 write_flash 0x0 " & bin0 & " 0x10000 " & bin1

task setup, "Generate local nim.cfg for IDE support":
  let cfgContent = "# Generated by 'nim setup'\n" &
                   "--path: \"" & helperDir & "\"\n" &
                   "--cpu:riscv32\n" &
                   "--os:any\n" &
                   "--mm:arc\n" &
                   "--define:noSignalHandler\n" &
                   "--define:dynlibOverrideAll\n" &
                   "--define:useMalloc\n" &
                   "--passC:\"-mlongcalls\"\n" &
                   "--passC:\"-mtext-section-literals\"\n" &
                   "--passC:\"-DICACHE_FLASH\"\n"
  
  var finalCfg = cfgContent
  if fileExists("src/sdkconfig.h"):
    finalCfg &= "--passC:\"-include src/sdkconfig.h\"\n"
  elif fileExists("sdkconfig.h"):
    finalCfg &= "--passC:\"-include sdkconfig.h\"\n"
  else:
    finalCfg &= "--passC:\"-include " & (helperDir / "default_sdkconfig.h") & "\"\n"

  writeFile("nim.cfg", finalCfg)
  echo "Generated nim.cfg for IDE support."
